### ISSUE TITLE
Create nw.js app

### ISSUE THREAD

**Issue by jadonk** [jadonk/beaglebone-getting-started#8]
There should be a simple getting-started application that includes all the information and tools needed to get started with BeagleBone in a single executable for each of Mac, Linux (x86 and ARM) and Windows.

**Comment by jadonk** [comment]
https://github.com/jadonk/beaglebone-getting-started/tree/node-webkit-app/app is one possible building block. Size needs to be a consideration.

**Comment by arianepaola** [comment]
Hello @jadonk

I have added a pull request #9 as part of my GSoC 2015 application to work on the BeagleBone Getting Started app.

It contains a grunt script to build the BeagleBone Getting Started app using the latest nw.js release.
The script downloads automatically nw.js for each platform and builds the application.


Thanks, Ariane

**Comment by arianepaola** [comment]
Hello @jadonk 

I have included your comments and create a pull request #10 

Thanks, Ariane

**Comment by jadonk** [comment]
I meant to comment here. Should this issue be closed?

**Comment by arianepaola** [comment]
Yes.
